# This is a basic workflow to help you get started with Actions

name: builder

# git push --tags 执行时候进行编译
on:
  push:
    tags:
      - v*


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.1
        with: 
            java-version: "12.x"

      - name: Flutter action
        uses: subosito/flutter-action@v2.7.1
        with:
            flutter-version: 3.3.2
            channel: stable
      - run: flutter pub get
      # 打包apk
      - run: flutter build apk --release --split-per-abi
      - name: Release Apk
        uses: ncipollo/release-action@v1.10.0
        with:
            artifacts: "build/app/outputs/flutter-apk/app-*.apk"
            token: ${{secrets.RELEASE_TOKEN}}

      # 打包linux-x64
      #- run: flutter build linux --release --target-platform linux-x64
      #- run: cd  build/linux/x64/release
      #- run: tar zcf linux-x64.
      # 打包linux-arm64
      #- run: flutter build linux --release --target-platform linux-arm64
      # 打包web
      #- run: flutter build web --release
