# This is a basic workflow to help you get started with Actions

name: builder

# git push --tags 执行时候进行编译
on:
  push:
    tags:
      - v*


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.1
        with: 
            distribution: 'zulu'
            java-version: "17"
            token: ${{secrets.RELEASE_TOKEN}}

      - name: Flutter action
        uses: subosito/flutter-action@v2.7.1
        with:
            flutter-version: 3.7.0-1.5.pre
            channel: beta

      - run: flutter pub get
      # 打包apk
      - run: flutter build apk --release --split-per-abi

      # 打包linux-x64
      - run: sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter build linux --release --target-platform linux-x64

      # 复制linux二进制文件到AppDir目录,准备打包
      - run: rm -rf AppDir || true
      - run: cp -r build/linux/x64/release/bundle AppDir
      # 打包成AppImage
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage@v1
        with:
          recipe: "./AppImageBuilder.yml"
          
      # 发布安装包
      - name: Release Packages
        uses: ncipollo/release-action@v1.10.0
        with:
            artifacts: "build/app/outputs/flutter-apk/app-*.apk,Jibo-release-linux-x64-x86_64.AppImage"
            token: ${{secrets.RELEASE_TOKEN}}
